# Test your FastAPI endpoints

GET http://127.0.0.1:7000/
Accept: application/json

###

GET http://127.0.0.1:7000/create_model/model2
Accept: application/json

###

GET http://127.0.0.1:7000/fit_model/model2
Accept: application/json

###

GET http://127.0.0.1:7000/predict_all/model2
Accept: application/json

###

POST http://127.0.0.1:7000/predict/model2
Accept: application/json
Content-Type: application/json

{
  "installment": 829.10,
  "log_annual_inc": 11.350407,
  "dti": 19.48,
  "fico": 737,
  "revol_bal": 28854,
  "revol_util": 52.1,
  "inq_last_6mths": 0,
  "delinq_2yrs": 0,
  "pub_rec": 0
}
###
